# Generated by Django 4.1.6 on 2023-02-07 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamerraterapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='categories',
            field=models.ManyToManyField(through='gamerraterapi.GameCategory', to='gamerraterapi.category'),
        ),
    ]
