# Generated by Django 4.1.6 on 2023-02-13 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamerraterapi', '0002_alter_gamerating_date_rated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamereview',
            name='date_reviewed',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
