# Generated by Django 4.1.6 on 2023-02-13 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamerraterapi', '0003_alter_gamereview_date_reviewed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamerating',
            old_name='rating',
            new_name='user_rating',
        ),
    ]
